on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: main
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install python3-pip
          sudo apt install python3.8-venv
          python3 -m venv ansible-playbook && . ansible-playbook/bin/activate && pip3 install --upgrade pip && pip3 install wheel
          pip3 install ansible==2.10.0
          ansible-galaxy collection install azure.azcollection
          pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
          mkdir /home/runner/.azure
          cp main/ansible/keys/azureProfile.json /home/runner/.azure
          cp main/ansible/keys/credential  /home/runner/.azure
          cp main/ansible/keys/service_principal_entries.json /home/runner/.azure
          sudo apt install azure-cli
          az login --service-principal --username c6a0385a-1cd7-4673-a516-22194f97fa23 --tenant 0634f583-e93e-4a11-9749-058651409f10 --password Tv.XitBa6tvKg.WZu~zgXUIhrEvGo9xA50
      - name: Create Azure Resource Group with Ansible Playbook
        run: |
          ./ansible-playbook/bin/ansible-playbook main/ansible/playbook/create_rg_azcollection.yml -vvv
           
        
          

 
