on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: main
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
      - name: Install Ansible
        run: |
          sudo apt update
          sudo pip install ansible
          sudo apt install python3-pip
          sudo pip install "pywinrm>=0.3.0"
          sudo ansible-galaxy install azure.azure_preview_modules
          sudo wget -nv -q https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
          sudo pip install -r requirements-azure.txt
      - name: List Working Directory
        run: |
          ls -R
      - name: Create Azure Resources
        run: |
          ansible localhost -m azure.azcollection.azure_rm_resourcegroup -a "name=test-kiratech location=westeurope"
           
        
          

 
