on: [push]

name: AnsibleAzure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: main
      - name: Azure Login
        uses: azure/login@v1
        with:
          enable-AzPSSession: true
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Print Credentials 
        run: |
          secretid=echo "${{ secrets.VAR_CLIENT_ID }}" | sed 's/./& /g'
          sed -i 's/VAR_CLIENT_ID/${secredit}/g' main/ansible/keys/credentials
          cat main/ansible/keys/credentials
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            set -ex
            ls ~/.azure
            cat ~/.azure/versionCheck.json
            az --version
            az account show
            az group list
      - name: Install Ansible
        env: 
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          sudo apt update
          sudo apt install python3-pip
          sudo apt install python3.8-venv
          python3 -m venv ansible-playbook && . ansible-playbook/bin/activate && pip3 install --upgrade pip && pip3 install wheel
          pip3 install ansible==2.10.0
          ansible-galaxy collection install azure.azcollection
          pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
          ./ansible-playbook/bin/ansible --version
      - name: Create Azure Centos Vm with Ansible Playbook
        run: |
          ./ansible-playbook/bin/ansible-playbook main/ansible/playbook/create_centos_vm_azure.yml -vvv
           
        
          

 
