on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: main
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt remove ansible
          sudo pip3 install ansible
          sudo apt install python3-pip
          sudo pip3 install msrest
          sudo pip3 install msrestazure
          sudo pip3 install ansible[azure]
          sudo ansible-galaxy collection install azure.azcollection --force
          python --version
      - name: List Working Directory
        run: |
          ls -R
      - name: Create Azure Resources
        run: |
          sudo ansible --version
          /usr/local/bin/ansible localhost -m azure.azcollection.azure_rm_resourcegroup -a "name=test-kiratech location=westeurope"
          sudo ansible localhost -m azure.azcollection.azure_rm_resourcegroup -a "name=test-kiratech location=westeurope"
           
        
          

 
