on: [push]

name: CI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install ansible -y
          pwd
 
