on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        working-directory: ./ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install ansible -y
          pwd
          pip install ansible[azure]
          ls
          cd /home/runner/work/kiratech_challenge/kiratech_challenge/main
      - name: Create Azure Resources
        run: |
          ansible-playbook virtualcentosazure.yaml
          working-directory: ${{env.working-directory}}
          

 
