on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        working-directory: ansible
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: main
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install ansible -y
          pwd
          pip install ansible[azure]
          ls -R
          ls -la
      - name: List Working Directory
        run: |
          ls -R
      - name: Create Azure Resources
        working-directory: ${{env.working-directory}}
        run: |
          ansible-playbook virtualcentosazure.yaml
        
          

 
