on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: main
      - name: Azure Login
        uses: azure/login@v1
        with:
          enable-AzPSSession: true
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Print Credentials 
        run: |
          echo "${{secrets.AZURE_CREDENTIALS.subscription_id}}" | sed 's/./& /g'
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            set -ex
            ls ~/.azure
            cat ~/.azure/versionCheck.json
            az --version
            az account show
            az group list
      - name: Install Ansible
        env: 
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          sudo apt update
          sudo apt install python3-pip
          sudo apt install python3.8-venv
          python3 -m venv ansible-playbook && . ansible-playbook/bin/activate && pip3 install --upgrade pip && pip3 install wheel
          pip3 install ansible==2.10.0
          ansible-galaxy collection install azure.azcollection
          pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
          ./ansible-playbook/bin/ansible --version
          export AZURE_SUBSCRIPTION_ID=$(${{ secrets.AZURE_CREDENTIALS.subscription_id}})
          export AZURE_CLIENT_ID=$$(${{ secrets.AZURE_CREDENTIALS.client_id }})
          export AZURE_SECRET=$(${{ secrets.AZURE_CREDENTIALS.secret}})
          export AZURE_TENANT=$(${{ secrets.AZURE_CREDENTIALS.tenant }})
      - name: Create Azure Centos Vm with Ansible Playbook
        run: |
          ./ansible-playbook/bin/ansible-playbook main/ansible/playbook/create_centos_vm_azure.yml -vvv
           
        
          

 
