on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      env: # Or as an environment variable
        credentials: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: main
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install curl
          sudo apt install python3-pip
          sudo apt install python3.8-venv
          python3 -m venv antenv
          sudo apt install ansible
          source antenv/bin/activate
          ansible --version
          pip install azure-cli
          pip install msrest
          pip install msrestazure
          pip install ansible[azure]
          curl -O https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
          pip install -r requirements-azure.txt
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Create Azure Resource Group with Ansible Playbook
        run: |
          ansible-playbook main/ansible/playbook/create_rg.yml --extra-vars "name=test-kira location=westeurope" -vvv
           
        
          

 
